version: '3'
 
services:
  virt-manager:
    build: .
    image: desktopcontainers/virt-manager
    network_mode: bridge
    restart: always
    environment:
      SERVER_NAME: localhost

      VNC_SCREEN_DEPTH: 24

      #ENABLE_SUDO: enable
      #ENABLE_KIOSK: enable
    volumes:
      - ~/.ssh:/home/app/.ssh:ro
    ports:
      - 22
