version: '3'
 
services:
  virt-manager:
    build: .
    image: desktopcontainers/virt-manager
    network_mode: bridge
    restart: always
    environment:
      SERVER_NAME: localhost

      VNC_SCREEN_DEPTH: 24

      #ENABLE_SUDO: enable
      #ENABLE_KIOSK: enable
    volumes:
      - ~/.ssh:/home/app/.ssh:ro
#      - ./certs:/certs
    ports:
      - "22"
#      - "8080:80"
#      - "4443:443"
#      - "5900:5900"